"""new word len

Revision ID: 174df975cc58
Revises: d9d97d61c147
Create Date: 2024-04-12 13:22:48.408029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174df975cc58'
down_revision = 'd9d97d61c147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
