"""Added relations table

Revision ID: 98017b794433
Revises: f829c44325db
Create Date: 2024-01-29 00:08:18.005550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98017b794433'
down_revision = 'f829c44325db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_token_id', sa.Integer(), nullable=False),
    sa.Column('target_token_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['source_token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['target_token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation')
    # ### end Alembic commands ###
