"""Added start and end to Token

Revision ID: a59d01b4ed39
Revises: 92fb2e4d05d0
Create Date: 2024-01-24 20:44:16.889066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59d01b4ed39'
down_revision = '92fb2e4d05d0'
branch_labels = None
depends_on = None


from sqlalchemy import text

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.Integer()))
        batch_op.add_column(sa.Column('end', sa.Integer()))

    op.execute(text("""UPDATE token SET start = 0, "end" = 0"""))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('word', existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.drop_column('end')
        batch_op.drop_column('start')
    # ### end Alembic commands ###
