"""new word lengthg

Revision ID: ef228720c63f
Revises: 7b8e8fc813fb
Create Date: 2024-04-12 13:37:16.790225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef228720c63f'
down_revision = '7b8e8fc813fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
