"""unique change

Revision ID: f829c44325db
Revises: a59d01b4ed39
Create Date: 2024-01-24 20:54:16.623438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f829c44325db'
down_revision = 'a59d01b4ed39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('start',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('token_word_key', type_='unique')
        batch_op.drop_constraint('token_word_key1', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.create_unique_constraint('token_word_key1', ['word'])
        batch_op.create_unique_constraint('token_word_key', ['word'])
        batch_op.alter_column('end',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('word',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
